---
- name: Get root user info
  getent:
    database: passwd
    key: '1000'
    fail_key: false
- debug:
    var: ansible_facts.getent_passwd
  
- name: Create the cvmfs user with UID 1000 if it doesn't exist
  user:
    name: cvmfs
    uid: 1000
    group: users
    state: present
  when: ansible_facts.getent_passwd[0] == ''
    
- include: client_install_centos.yml
  when: ansible_os_family == "RedHat"

- include: client_install_ubuntu.yml
  when: ansible_os_family == "Debian"
